name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install uv
        run: pip install uv

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}

      - name: Set up virtual environment
        run: |
          uv venv .venv
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install project and Sphinx dependencies
        run: |
          uv pip install -e . sphinx sphinx-rtd-theme sphinx-apidoc

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to README.rst
        run: pandoc README.md -o README.rst

      - name: Generate API docs and build HTML
        run: |
          sphinx-apidoc -o docs/source src
          make -C docs html

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/source/*
          git commit -m "Update Sphinx documentation" || echo "No changes to commit"
          git push origin ${GITHUB_REF} || echo "No changes to push"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
          keep_files: true
